[package]
name = "DataPipeline"
version = "0.1.0"
authors = ["Glenn Pierce <glenn.pierce@carnegosystems.com>"]

[dependencies]
pretty_env_logger = "0.1.0"
env_logger = "0.4.0"
log = "0.3.1"
time = "0.1.36"
chrono = "0.2"